server {
    listen ${PORT};
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://dummyjson.com/;
        proxy_set_header Host dummyjson.com;
        proxy_ssl_server_name on;
    }
}